### ISSUE TITLE
Cannot read generated code

### ISSUE THREAD

**Issue by AppWerft** [siciarek/javascript-qrcode#2]
Awesome  work!
I'm working in jsPDF environment and try to generate a QR inside PDF – it is similar to your [L46-L52](https://github.com/siciarek/javascript-qrcode/blob/master/bin/qrcode#L46-L52)

```
var qrcode = new (require('qrcode'))('tel:+494060812460',['L'],1);
var code = qrcode.getData();
doc.setDrawColor(1); doc.setFillColor(1);
for (var r = 0; r < code.length; r += 1) 
    for (var c = 0; c < code[r].length; c += 1) 
         if (code[r][c] === 1) 
            doc.rect(r * R, 9c * R, R, R, 'F');
```

This code builds:
![](http://i.imgur.com/SVw4Ko6.png)
This is output of getInfo():

```
{
capacity = 17;
data = "tel:+494060812460";
datalen = 17;
eclevel = L;
mode = binary;
pattern = 1;
version = 1;
}
```

**Comment by siciarek** [comment]
Thank you very much.

But I have to confess, I am a little bit confused with the title of your post.
Do you have any problem with javascript-qrcode?

**Comment by AppWerft** [comment]
Hello Jacek,

now it works. Little problem in the PSF world was the border of ever 
rectancle. My solution: the width is distance between rectangles \* 1.01. 
It is enaough to cover the border.

for (var r = 0; r < code.length; r += 1) {
             for (var c = 0; c < code[r].length; c += 1) {
                 if (code[r][c] === 1) {
                     /*1% more size to cover the border of rect. */
                     doc.rect(5 + r \* R, 95 + c \* R, R \* 1.01, R \* 1.01, 
'F');
                 }
             }
         }

Best regards

Rainer

Am 27/08/15 um 10:10 schrieb Jacek Siciarek:

> Thank you very much.
> 
> But I have to confess, I am a little bit confused with the title of 
> your post.
> Do you have any problem with javascript-qrcode?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/siciarek/javascript-qrcode/issues/2#issuecomment-135335349.

## 

_Dipl.-Ing. Rainer Schleevoigt_
Certified TYPO3 Integrator
Certified Titanium App Developer

```
Novalisweg 10
```

22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by siciarek** [comment]
Ok

**Comment by AppWerft** [comment]
Hi Siciarek,

I have tested with 6 Scanners on iOS and Android and I'm  ti say, it works only in 3 cases. I don't why. I have played with ec level, but no help. Perhaps an issue with version?

Cheers!

Rainer

**Comment by siciarek** [comment]
I have to confess that I used only two android scanners and zbarimg and it
worked fine, sometimes it failed but only with very large size qrcodes.
I have tests for all the features so you can run the tests:

http://siciarek.pl/qrcode/qunit/index.src.html

or try to use the demo application

http://siciarek.pl/qrcode/

If the application will have the same results as yours, do not hesitate to
notify me.

Best regards

Jacek Siciarek

**Comment by AppWerft** [comment]
Hi Jacek,

I have tested your http://siciarek.pl/qrcode/ and all variants works 
with my scanners.

my modifications of your code:
1. embedding you r code in 'module.exports' to encapsulate  (I don't so 
   a problem.)
2. using of jspdf lib to render
   if in your matrix is a '1' then I generate a black square else the 
   background keeps white

Currently I don't see a solution.

Wielkie dzięki!

Rainer

Am 28/08/15 um 11:07 schrieb Jacek Siciarek:

> I have to confess that I used only two android scanners and zbarimg and it
> worked fine, sometimes it failed but only with very large size qrcodes.
> I have tests for all the features so you can run the tests:
> 
> http://siciarek.pl/qrcode/qunit/index.src.html
> 
> or try to use the demo application
> 
> http://siciarek.pl/qrcode/
> 
> If the application will have the same results as yours, do not hesitate to
> notify me.
> 
> Best regards
> 
> Jacek Siciarek
> 
> On Fri, Aug 28, 2015 at 10:50 AM, Rainer Schleevoigt <
> notifications@github.com> wrote:
> 
> > Hi Siciarek,
> > 
> > I have tested with 6 Scanners on iOS and Android and I'm ti say, it 
> > works
> > only in 3 cases. I don't why. I have played with ec level, but no help.
> > Perhaps an issue with version?
> > 
> > Cheers!
> > 
> > Rainer
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/siciarek/javascript-qrcode/issues/2#issuecomment-135686830
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/siciarek/javascript-qrcode/issues/2#issuecomment-135698772.

## 

_Dipl.-Ing. Rainer Schleevoigt_
Certified TYPO3 Integrator
Certified Titanium App Developer

```
Novalisweg 10
```

22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||
